### ISSUE TITLE
Cyrillic abbreviation

### ISSUE THREAD

**Issue by EMDM45** [ponysmith/brevity#3]
Doesn't work with cyrillic abbreviation
Example here:
https://codepen.io/emdm/pen/ZEappGd

**Comment by EMDM45** [comment]
To resolve this issue, can add option like 'cyrillic'. If `true`, then regexp will be `"(?<=\\s|^)" + a.abbr + "(?=\\s|$)"`

**Comment by ponysmith** [comment]
Thanks for the suggestion. Multibyte strings should be supported now in the v2.0.0 release.
